# Site settings
lang: en
locale: en_US

# Theme
# Use the So Simple theme via remote_theme so GitHub Pages can build it.
remote_theme: mmistakes/so-simple-theme

# Site metadata
title: "PL @ LX"
description: "Informal programming language design and implementation community in Lisbon"
url: "https://gabmeirinho.github.io"
baseurl: ""

# Owner information displayed in theme footer
author:
  name: "PL @ LX"
  location: "Lisbon, Portugal"

# Footer social/profile links
footer_links:
  - label: "Mailing List"
    icon: "fas fa-envelope"
    url: "https://groups.google.com/g/pl_lx/"
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/gabmeirinho"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Collections (none for now)
collections:
  posts:
    output: true
